defmodule Mix.Tasks.Guard.Sign do
  @shortdoc "Signs the compiled ChorusDraft Guard modules"

  @moduledoc """
  Records a digest of each compiled Guard module and signs it with an ed25519
  key.

      CHORUSDRAFT_GUARD_SIGNING_KEY=/secure/path/release.key mix guard.sign

  The signing key comes from `--key PATH` or `CHORUSDRAFT_GUARD_SIGNING_KEY`.
  The signed manifest, its signature, and the public keys in `guard/keys/` are
  compiled into the build, and a copy of the manifest and signature is written
  to `guard/guard.manifest` and `guard/guard.manifest.sig` as the record of
  what was signed. Guard is verified against the signature at runtime, so a
  build has to be signed after Guard is compiled, and signed again whenever
  Guard changes.

  `--development` signs with a key kept in `_build/` and trusts it through
  `guard/keys/development.pub` when no release key is configured. That is how
  the test suite and unofficial builds get a working Guard; it proves nothing
  about a downloaded release, which is why an official build refuses to keep a
  development key alongside the release key.
  """

  use Mix.Task

  alias ChorusDraft.Guard
  alias ChorusDraft.Guard.Signature

  @development_public "guard/keys/development.pub"

  @impl Mix.Task
  def run(argv) do
    {options, [], []} = OptionParser.parse(argv, strict: [key: :string, development: :boolean])

    Mix.Task.run("compile")

    root = Path.expand("../..", Mix.Project.build_path())
    {private_key, kind} = signing_key(root, options)

    manifest = Signature.manifest_text(beams(), ChorusDraft.version())
    signature = Signature.encode_signature(Signature.sign(manifest, private_key))

    write(Path.join(root, "guard/guard.manifest"), manifest)
    write(Path.join(root, "guard/guard.manifest.sig"), signature)
    bundle(manifest, signature, trusted_keys(root))

    case kind do
      :release ->
        Mix.shell().info("Signed Guard for ChorusDraft #{ChorusDraft.version()}")

      :development ->
        Mix.shell().info(
          "Signed Guard for ChorusDraft #{ChorusDraft.version()} with a development key (unofficial build)"
        )
    end
  end

  # The signature covers code that only exists once Guard has been compiled, so
  # it cannot be a compile-time input to the build it describes. Signing writes
  # its own module into the build instead: escript packaging picks it up with
  # the rest, and a build that was never signed simply does not have it.
  defp bundle(manifest, signature, keys) do
    source = """
    # Generated by mix guard.sign. Sign again to replace it.
    defmodule ChorusDraft.Guard.Signature.Bundle do
      @moduledoc false
      def manifest, do: #{inspect(manifest)}
      def signature, do: #{inspect(signature)}
      def trusted_keys, do: #{inspect(keys, binaries: :as_binaries, limit: :infinity)}
    end
    """

    previous = Code.compiler_options(ignore_module_conflict: true)

    try do
      [{module, beam}] = Code.compile_string(source)
      File.write!(Path.join(Mix.Project.compile_path(), "#{module}.beam"), beam)
    after
      Code.compiler_options(previous)
    end
  end

  defp beams do
    Enum.map(Guard.modules(), fn module ->
      Code.ensure_loaded(module)

      case :code.get_object_code(module) do
        {^module, beam, _path} -> {module, beam}
        :error -> Mix.raise("Compiled Guard module #{inspect(module)} was not found")
      end
    end)
  end

  defp signing_key(root, options) do
    development_public = Path.join(root, @development_public)

    case options[:key] || System.get_env("CHORUSDRAFT_GUARD_SIGNING_KEY") do
      nil ->
        unless options[:development] do
          Mix.raise("""
          No Guard signing key. Set CHORUSDRAFT_GUARD_SIGNING_KEY (or pass --key PATH)
          to a key from `mix guard.keygen`, or run `mix guard.sign --development` to
          sign an unofficial build with a development key.
          """)
        end

        private_key = development_key()
        write(development_public, Signature.encode_public_key(Signature.public_key(private_key)))
        {private_key, :development}

      path ->
        if File.exists?(development_public) do
          Mix.raise(
            "Delete #{@development_public} before signing with a release key: an official build must not also trust a development key."
          )
        end

        private_key = read_key(path)
        public_key = Signature.public_key(private_key)

        unless public_key in trusted_keys(root) do
          Mix.shell().error(
            "Warning: no file in guard/keys/ matches this signing key, so the build will refuse the Guard it just signed. Add the public key from `mix guard.keygen` and compile again."
          )
        end

        {private_key, :release}
    end
  end

  # One key for every MIX_ENV of this checkout, kept out of the source tree.
  defp development_key do
    path = Path.join(Path.dirname(Mix.Project.build_path()), "guard-development.key")

    if File.exists?(path) do
      read_key(path)
    else
      private_key = :crypto.strong_rand_bytes(32)
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, Signature.encode_private_key(private_key))
      File.chmod!(path, 0o600)
      private_key
    end
  end

  defp read_key(path) do
    case File.read(path) do
      {:ok, text} ->
        case Signature.parse_private_key(text) do
          {:ok, private_key} -> private_key
          :error -> Mix.raise("#{path} is not an ed25519 signing key")
        end

      {:error, reason} ->
        Mix.raise("Cannot read signing key #{path}: #{:file.format_error(reason)}")
    end
  end

  defp trusted_keys(root) do
    root
    |> Path.join("guard/keys/*.pub")
    |> Path.wildcard()
    |> Enum.flat_map(fn path ->
      case Signature.parse_public_key(File.read!(path)) do
        {:ok, key} -> [key]
        :error -> []
      end
    end)
  end

  defp write(path, contents) do
    unless File.read(path) == {:ok, contents} do
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, contents)
    end
  end
end
